### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by Aeris1One** [JensenJ/SpaceRPG#1]
Looks promising !
Really love the door animation !

Are you planning to turn this into a real game or just using as a sandbox ? As this would be a really good game !

You can surely turn your Coridor-Test map into a maze 😁

Keep on going!

**Comment by JensenJ** [comment]
Hi, 
Thanks for the feedback. The idea of the project is to be a story-driven (potentially multiplayer) survival game. The corridors seen here are part of a tile set for a future base-building mechanic where the player will be able to build up their home area / base to survive in. Eventually AI characters will move into this base and the player will receive quests from them to progress the story.
